repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: no-commit-to-branch
  - id: check-added-large-files
  - id: check-yaml
    args: ['--unsafe']
  - id: check-toml
  - id: check-ast
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: name-tests-test
  - id: detect-private-key

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
      entry: codespell
      args:
        [
          "--ignore-words-list=py,",
          "--quiet-level=2",
          "--skip=./**/tests/**,./**/_test*.py,.git,*.ipynb,*.json,*.lock,*.txt,*.yaml",
        ]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.3
  hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

- repo: local
  hooks:
    - id: mypy
      name: check typing
      description: ""
      entry: mypy
      language: python
      types_or: [python, pyi]
      args: ["--ignore-missing-imports"]
      require_serial: true
